### ISSUE TITLE
VEM for Stokes  problem

### ISSUE THREAD

**Issue by Yanwei-LI-sd** [Terenceyuyue/mVEM#3]
Dear teacher. I am LI Yanwei, a graduate student in Shandong Normal University, and I am currently working on the project of virtual element related to Stokes problem. I am very glad to see the code about virtual element written by you on GitHub.I have been keeping an eye on your code update. Will you write VEM code about Stokes problem in the future? It's my pleasure that you update the code about stokes problem.

**Comment by Terenceyuyue** [comment]
Hi, Li!

    I am a graduating PhD. 

    I'm busy with the graduation process and have no time to consider your request at this time.

    I shall write the vem code for Stokes problem in the next two months.  

    And I will upload the PDF documents as soon as possible.


   Terence Yu, 2021/05/25

    



----- 原始邮件 -----
发件人: "Yanwei-LI-sd" ***@***.***>
收件人: "Terenceyuyue/mVEM" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期二, 2021年 5 月 25日 下午 4:34:08
主题: [Terenceyuyue/mVEM] VEM for Stokes  problem (#3)

Dear teacher. I am LI Yanwei, a graduate student in Shandong Normal University, and I am currently working on the project of virtual element related to Stokes problem. I am very glad to see the code about virtual element written by you on GitHub.I have been keeping an eye on your code update. Will you write VEM code about Stokes problem in the future? It's my pleasure that you update the code about stokes problem.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Terenceyuyue/mVEM/issues/3

**Comment by Yanwei-LI-sd** [comment]
Hi, Yu!
Thank you for the reply.
It's great! I shall look forward to your update. Best wishes and congratulations on your graduation.
Thank you once again!

**Comment by Yanwei-LI-sd** [comment]
Hi, Yu!
    Best wishes and congratulations on your graduation. Are you busy these days? 

    I recently tried to write vem code for Stokes peoblem. But I couldn't successfully implement the code. 

    I want to ask when you can update the code or PDF.

    Looking forward to your reply! Thank you very much!

   
    Yanwei Li, 2021/08/05

**Comment by Terenceyuyue** [comment]
Sorry !  

I am working as a Postdoc on a new area  which is very different from my previous knowledge.

I need to learn a lot. 

I won't consider updating the code until the middle of this month. 

I suggest you a reference:  Mixed Virtual Element Methods. Applications in Fluid Mechanics.  (Author: Ernesto David Caceres Valenzuela)

If you have any problems in writing the code, you can contact me at any time.

Advice:   Figure out all the details before you  write the code. 

Terence,  2021/08/05

**Comment by Yanwei-LI-sd** [comment]
OK!

Thank you for your advice. 

I've finished my code, but when I run it, MATLAB tells me that the matrix is close to singularity. So the result is uncorrect. And I haven't been able to find the error. I haven't made any progress in a long time.

I will read the reference that you recommended. Then I'm going to modify my code. 

Thank you once again!

**Comment by Terenceyuyue** [comment]
Hi, Li!

The mixed VEM for Stokes problem has been added. 
Sorry for  the unpunctuality!

**Comment by Yanwei-LI-sd** [comment]
HI, Yu!

Thank you very much!

I have seen the PDF and code you uploaded! This is very helpful to my problem! I am a first-year graduate student and the mixed VEM for Stokes problem code is my first code in graduate school. Thank you for your great help! 

I will take a good look at the PDF and the code. 

Thank you once again! Wish you a happy life and smooth work!

Yanwei Li, 2021/08/16

**Comment by MathPoincare** [comment]
Hi, Li
i hope you are okay, i'am also  a graduate student, and i  also working on the project of virtual element related to Stokes problem, so can u share with me the code source, thanks
