### ISSUE TITLE
关于网格的加密

### ISSUE THREAD

**Issue by Yanwei-LI-sd** [Terenceyuyue/mVEM#5]
您好，很抱歉再次打扰到您。
我想向您咨询下关于网格加密的问题，这个问题我觉着用英文不太好描述，所以用中文给您留言。
在计算收敛阶的时候，我们需要对网格逐渐的加密，您写的代码里一直用的Voronoi图，而且给了32--10000的网格数据。我看了您的PDF里面关于“网格加密”的部分，用PolyMeshRefine函数对已知的网格加密，关于这个地方我有点疑问，按照您给的，图2是图1的加密，可是我想用PolyMeshRefine函数对图1进行加密却得到了图三。我想问下怎么通过图1加密成图2，我想自己加密一些网格，比如您给的'distortionPolygon.mat'这个网格数据，我想计算下在这个网格下的收敛阶，怎么对网格进行加密？
如果打扰到您还请见谅。十分感谢！
另外，我之前问过您的关于Stokes方程虚拟元提升空间的问题已经解决了，谢谢您对我的指导和帮助。
![1](https://user-images.githubusercontent.com/84770266/134305525-790ac9a0-f54c-49b6-866d-08cf0c4214f0.jpg)
![2](https://user-images.githubusercontent.com/84770266/134305532-4831d747-6823-4d6c-968f-700708931f86.jpg)
![3](https://user-images.githubusercontent.com/84770266/134305536-26e24ae4-0ff6-4d78-8ef8-0a3923bf63ce.jpg)

**Comment by Terenceyuyue** [comment]
（1）网格数据中给出的比如32,64等等，不是在某个剖分基础上继续加密，而是把一个区域剖分为32或64个单元的网格；

（2）二维网格剖分已经有文章给出了，我稍微改动了一下。你可以查看 mesh/PolyMesher/meshfun，它生成指定单元个数的多角形剖分；

（3）文献中网格生成使用的是 Voronoi 图，我在 PDF 文档中也详细说明了，感兴趣你可以参考。Delaunay 三角和 Voronoi 图是网格生成的基础；

（3）Polymeshrefine.m 是在某个网格的基础上进行加密，主要用于自适应算法。

**Comment by Yanwei-LI-sd** [comment]
您好，我又重新看了下您说的地方，还有个小问题向您请假一下：

meshfun.m是只能生成Voronoi图为基础的网格剖分吗？如果我想生成一些正六边形剖分或者一些非凸的多边形剖分可以在这个函数的基础上进行改动吗？

**Comment by Terenceyuyue** [comment]
特殊网格自己手动生成就好，比如把四边形网格的边往外拉扯增加节点。注意，网格剖分通常都是希望生成高质量的网格，而不是制造不必要的麻烦。只是说，对某些数值方法，我们希望对糟糕的网格也有效。另外，如果区域比较差，那么网格可能差。网格加密通常也会出现不好的网格。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月22日(周三) 晚上8:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Terenceyuyue/mVEM] 关于网格的加密 (#5)




 
您好，我又重新看了下您说的地方，还有个小问题向您请假一下：
 
meshfun.m是只能生成Voronoi图为基础的网格剖分吗？如果我想生成一些正六边形剖分或者一些非凸的多边形剖分可以在这个函数的基础上进行改动吗？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Yanwei-LI-sd** [comment]
您好，很抱歉再次打扰到您。

我想向您咨询下如何画Stokes方程带箭头的向量图（如图1）。不知道您对这个有了解吗？

目前我尝试画了几次，都感觉不是很对。我画向量图的想法是，考虑二维的Stokes流体，u是一个二维向量（u_1;u_2），我把网格剖分的节点看成是向量的起点，在这个剖分节点上可以求得u_1和u_2的数值，我把u_1看作是向量终点的横坐标，把u_2看作是向量终点的纵坐标，调用MATLAB中的quiver函数，来画这个向量图。

由于我知识有限，也没从网上搜到相关的解答，所以冒昧来向您请教。不知您知道如何画这种图吗？希望不会打扰到您。

图2是我自己画的，我的真解取的为u=(u_1;u_2), u_1=4*(2y-1)*x*(1-x), u_2=-4*(2*x-1)*y*(1-y).

![velocity field](https://user-images.githubusercontent.com/84770266/138261965-d9d692dd-73be-4c94-ae41-22feee7e5261.png)
![my](https://user-images.githubusercontent.com/84770266/138261991-5f0ceb4e-56bf-49b7-8048-f7da9458baa8.png)

**Comment by Terenceyuyue** [comment]
你第三个图是如下生成的吗

load distortionSquare
x = node(:,1); y = node(:,2);
u = 4*(2*y-1).*x.*(1-x);
v = -4*(2*x-1).*y.*(1-y);
quiver(x,y,u,v);

这个图跟你 (x,y) 的位置有关系，网格匹配才能画出类似的图。

**Comment by Yanwei-LI-sd** [comment]
我当时是这样生成的，当时的网格选择的是900个单元的扭曲正方形网格，前两行代码是把网格数据转换成了meshgrid的形式，然后发现需要转置一次才能是想要的网格，然后提取出u_1和u_2，再利用quiver进行画图。
X=reshape(node(:,1),31,31);
Y=reshape(node(:,2),31,31);
X=X';Y=Y';
u1=reshape(uh(1:size(node,1),1),31,31);
u2=reshape(uh(NE+size(node,1)+1:2*size(node,1)+NE),31,31);
u1=u1';u2=u2';
quiver(X,Y,u1,u2)

**Comment by Yanwei-LI-sd** [comment]
您好，我画图的这个代码和您写的那个画出来是一样的，我想问下您说的 “画出的图跟( x,y)的位置有关，网格匹配才能画出来”是什么意思。这个向量图这样画可以吗，我不知道如何去验证这个图是否是正确的。

希望我的这些问题不会打扰到您，您有空的时候给我回复就可以了。特别感谢您对我的莫大的帮助。

**Comment by Terenceyuyue** [comment]
我的意思是跟你的网格有关系。流体一般都是画等值线图，看圈圈。这一般都是针对那些benchmark，特别是没有显式精确解的。验证算法是否正确，你可以先做有显式解的例子，说明误差等。之后，再看别人文章有没有好玩的例子，看看圈圈的中心和个数对不对就好了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月23日(周六) 上午10:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Terenceyuyue/mVEM] 关于网格的加密 (#5)




 
您好，我画图的这个代码和您写的那个画出来是一样的，我想问下您说的 “画出的图跟( x,y)的位置有关，网格匹配才能画出来”是什么意思。这个向量图这样画可以吗，我不知道如何去验证这个图是否是正确的。
 
希望我的这些问题不会打扰到您，您有空的时候给我回复就可以了。特别感谢您对我的莫大的帮助。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Yanwei-LI-sd** [comment]
您好，不好意思又来打扰您。我最近正在写VEM Stokes方程后验误差估计的程序，模仿着您写的Possion方程的avem来写的。我自己写了一个Stokes_mixedVEM_indicator.m和main_Stokes_avem.m文件，关于单元的标记还是用的您的mark.m文件。运行之后，关于速度的收敛阶正确，但是压力没有算对，每次网格加密后，压力的误差一直都是同一个数字，而且误差挺大，约为6.7（注：我用的算例是压力在原点处有奇异）。调试了很久不知道哪个地方出错了，实在求助无门，所以向您来请教，您觉着可能是什么地方没算对。
还有个不情之请，如果可以的话，您可以有空更新下Stokes_mixedVEM_avem的程序吗？我个人觉着这个程序有了前面的铺垫不是很难，奈何实力有限，我没有将其写出来。我参考的后验误差估计的文章为
https://link.springer.com/content/pdf/10.1007/s10915-020-01281-2.pdf
冒昧留言，打扰您的假期生活，还望海涵。提前祝您新年快乐，工作顺利。
